FORMAT: 1A
HOST: http://localhost:3000/api/

# FUCES API

FUCES API for mobile app.

## Allowed HTTPs requests

+ PUT     : Update resource
+ POST    : To create resource
+ GET     : Get a resource or list of resources
+ DELETE  : To delete resource

## Description Of Usual Server Responses

+ 200 OK - the request was successful (some API calls may return 201 instead).
+ 201 Created - the request was successful and a resource was created.
+ 204 No Content - the request was successful but there is no representation to return (i.e. the response is empty).
+ 400 Bad Request - the request could not be understood or was missing required parameters.
+ 401 Unauthorized - authentication failed or user doesn't have permissions for requested operation.
+ 403 Forbidden - access denied.
+ 404 Not Found - resource was not found.
+ 405 Method Not Allowed - requested method is not supported for resource.
+ 422 Unprocessable Entity - the request was well-formed but was unable to be followed due to semantic errors.

## Group Authentication

## Registrations [/auth/register]

### Register a new user [POST]

Create new users in the platform. It takes a JSON object containing the user information.

+ Attributes
    + email (required, string) - Email of the user in the form of a string
    + password (required, string) - Password of the user in the form of a string
    + isProfessional (boolean, optional)  - Set this parameter to true if the user will be registered as a Professional


+ Request (application/json)

        {
            "email": "user@flaxpro.ca",
            "password": "123456"
        }

+ Response 200 (application/json)

        {
            "token": "JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI1OTRiZGNkOTliMWJiNjJjZjU3ODlmZWEiLCJlbWFpbCI6InZpdmlhbm55c2RpYXN6dkBnbWFpbC5jb20iLCJyb2xlIjoiQ2xpZW50IiwiaWF0IjoxNDk4MTQzOTYxLCJleHAiOjE0OTgxNDQ1NjF9.j8HSW7Gw-6ryn5V1aHeTNyMQN0OmZsfcNaPng6IUUV0",
            "refreshToken": "594bdcd99b1bb62cf5789fea.872a3618f1e010f97c11453c40e21d158dcea1173d2bb762f4e53eb8c7acafa8ab8ea7271ca6043e",
            "user": {
                "_id": "594bdcd99b1bb62cf5789fea",
                "email": "user@flaxpro.ca",
                "role": "Client"
            }
        }
